const crudFormConfigs = {
  client: {
    fields: [
      {
        name: "isCompany",
        label: "Account Type",
        type: "select",
        required: true,
        options: [
          { value: "false", label: "Individual" },
          { value: "true", label: "Company" },
        ],
      },
      {
        name: "companyName",
        label: "Company Name",
        type: "text",
        required: false,
        help: "Required if account type is Company",
      },
      {
        name: "firstName",
        label: "First Name",
        type: "text",
        required: false,
        help: "Required if account type is Individual",
      },
      {
        name: "lastName",
        label: "Last Name",
        type: "text",
        required: false,
        help: "Required if account type is Individual",
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
      },
      {
        name: "password",
        label: "Password",
        type: "password",
        required: true,
        help: "Set an initial password for the new client user.",
      },
      { name: "phone", label: "Phone", type: "text", required: false },
      {
        name: "billingAddress",
        label: "Billing Address",
        type: "textarea",
        required: false,
      },
    ],
    submitLabel: "Save Client",
  },
  service: {
    fields: [
      {
        name: "service_name",
        label: "Service Name",
        type: "text",
        required: true,
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        required: false,
      },
      {
        name: "price",
        label: "Price",
        type: "number",
        required: true,
        pattern: "^\\d+(\\.\\d{1,2})?$",
        step: "0.01",
        min: "0",
      },
    ],
    submitLabel: "Save Service",
  },
  project: {
    fields: [
      {
        name: "client_id",
        label: "Client",
        type: "select",
        required: true,
        options: [],
        adminOnly: true,
      },
      {
        name: "services",
        label: "Services",
        type: "service-selector",
        required: true,
        help: "Select services for this project with quantities",
        services: [],
      },
      {
        name: "total_amount",
        label: "Total Amount",
        type: "number",
        required: false,
        pattern: "^\\d+(\\.\\d{1,2})?$",
        step: "0.01",
        min: "0",
        help: "Calculated automatically from selected services",
        readonly: true,
      },
      {
        name: "paid_amount",
        label: "Paid Amount",
        type: "number",
        required: false,
        pattern: "^\\d+(\\.\\d{1,2})?$",
        step: "0.01",
        min: "0",
        help: "Amount already paid by the client",
        adminOnly: true,
      },
      {
        name: "job_status",
        label: "Status",
        type: "select",
        required: true,
        options: [
          { value: "RECEIVED", label: "Received" },
          { value: "IN_PROGRESS", label: "In Progress" },
          { value: "COMPLETED", label: "Completed" },
          { value: "DELIVERED", label: "Delivered" },
        ],
        adminOnly: true,
      },
    ],
    submitLabel: "Save Project",
  },
};

module.exports = crudFormConfigs;
